version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
        environment:
          FLASK_CONFIG: test
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
            pip install pytest pytest-cov
      - run:
          command: |
            . venv/bin/activate
            pytest --cov=flask_accepts --cov-report xml --cov-report html
      - store_artifacts:
          path: htmlcov
      - codecov/upload:
          file: coverage.xml
